---
ip: "192.168.10.10"
memory: 2048
cpus: 1

forwarded_ports:
    http: 8000
    mysql: 3306
    postgresql: 5432

ssh:
  authorize: ~/.ssh/id_rsa.pub
  keys:
    - ~/.ssh/id_rsa

git-config:
    name: "Your Name"
    email: you@yourdomain.com